image: tmaier/docker-compose:latest

stages:
  - build
  - deploy
  - update_seeds

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

build:
  stage: build
  tags:
    - docker
  script:
    - docker-compose build

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - docker ps
    - docker-compose run api rake db:create db:migrate RAILS_ENV=production
    - docker-compose ps
    - docker-compose up -d --remove-orphans

replant_seeds:
  stage: update_seeds
  tags:
    - docker
  script:
    - docker-compose run api rake db:seed:replant RAILS_ENV=production DISABLE_DATABASE_ENVIRONMENT_CHECK=1
  when: manual
